### PR TITLE
add data types

### PR DESCRIPTION
**Pull request by ruslansenatorov**

### CODE REVIEW

**Comment by ruslansenatorov** [comment]
открой пул

**Comment by zatomaks** [comment]
где

**Comment by ruslansenatorov** [comment]
> где

внизу кнопка открыть

**Comment by ruslansenatorov** [comment]
**HERE**

**Review by ruslansenatorov — COMMENTED** [review]
elif assignment_percent > 60 and assignment_percent <= 70:
        messagebox.showinfo(
            "Results",
            f"Your current grade is {assignment_percent}%, which is a D. You can raise your grade by visiting {html_link}.",
        )
    else:
        messagebox.showinfo(
            "Results",
            f"You got an F with a low grade of {assignment_percent}%. You should immediatly visit {html_link} and start to study.",
        )


root = tk.Tk()
root.geometry("800x800")

num_assignments_label = tk.Label(
    root, text="How many assignments have been completed in the class so far?"
)
num_assignments_label.pack()

num_assignments_entry = tk.Entry(root)
num_assignments_entry.pack()

calculate_button = tk.Button(root, text="Calculate Grade", command=calculate_grade)
calculate_button.pack()

root.mainloop()

**Comment by zatomaks** [comment]
это что с этим сдлеать?

**Comment by ruslansenatorov** [comment]
> это что с этим сдлеать?

открой пул реквст, ВНИЗУ КНОПКА

**Comment by zatomaks** [comment]
image

**Comment by ruslansenatorov** [comment]
ТЫК #2

**Pull request merged**
